<a href="https://colab.research.google.com/github/gromag/natural-language-processing/blob/master/week4/week4-seq2seq.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Learn to calculate with seq2seq model

In this assignment, you will learn how to use neural networks to solve sequence-to-sequence prediction tasks. Seq2Seq models are very popular these days because they achieve great results in Machine Translation, Text Summarization, Conversational Modeling and more.

Using sequence-to-sequence modeling you are going to build a calculator for evaluating arithmetic expressions, by taking an equation as an input to the neural network and producing an answer as it's output.

The resulting solution for this problem will be based on state-of-the-art approaches for sequence-to-sequence learning and you should be able to easily adapt it to solve other tasks. However, if you want to train your own machine translation system or intellectual chat bot, it would be useful to have access to compute resources like GPU, and be patient, because training of such systems is usually time consuming. 

### Libraries

For this task you will need the following libraries:
 - [TensorFlow](https://www.tensorflow.org) — an open-source software library for Machine Intelligence.
 
In this assignment, we use Tensorflow 1.15.0. You can install it with pip:

    !pip install tensorflow==1.15.0
     
 - [scikit-learn](http://scikit-learn.org/stable/index.html) — a tool for data mining and data analysis.
 
If you have never worked with TensorFlow, you will probably want to read some tutorials during your work on this assignment, e.g. [Neural Machine Translation](https://www.tensorflow.org/tutorials/seq2seq) tutorial deals with very similar task and can explain some concepts to you. 

In [3]:
%tensorflow_version 1.x
import tensorflow
print(tensorflow.__version__)

TensorFlow 1.x selected.
1.15.2


In [1]:
try:
    import google.colab
    IN_COLAB = True
except:
    IN_COLAB = False

if IN_COLAB:
    ! wget https://raw.githubusercontent.com/hse-aml/natural-language-processing/master/setup_google_colab.py -O setup_google_colab.py
    import setup_google_colab
    setup_google_colab.setup_week4()

--2021-10-23 09:25:08--  https://raw.githubusercontent.com/hse-aml/natural-language-processing/master/setup_google_colab.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1939 (1.9K) [text/plain]
Saving to: ‘setup_google_colab.py’

setup_google_colab. 100%[===================>]   1.89K  --.-KB/s    in 0s      

2021-10-23 09:25:09 (27.0 MB/s) - ‘setup_google_colab.py’ saved [1939/1939]



### Data

One benefit of this task is that you don't need to download any data — you will generate it on your own! We will use two operators (addition and subtraction) and work with positive integer numbers in some range. Here are examples of correct inputs and outputs:

    Input: '1+2'
    Output: '3'
    
    Input: '0-99'
    Output: '-99'

*Note, that there are no spaces between operators and operands.*


Now you need to implement the function *generate_equations*, which will be used to generate the data.

In [2]:
import random

In [4]:
import operator

def generate_equations(allowed_operators, dataset_size, min_value, max_value):
    """Generates pairs of equations and solutions to them.
    
       Each equation has a form of two integers with an operator in between.
       Each solution is an integer with the result of the operation.
    
        allowed_operators: list of strings, allowed operators.
        dataset_size: an integer, number of equations to be generated.
        min_value: an integer, min value of each operand.
        max_value: an integer, max value of each operand.

        result: a list of tuples of strings (equation, solution).
    """
    # STUDENT CODE      
    operations = { "+": operator.add, "-": operator.sub }
    # Note: we may end up with an equation with unusual
    # notation like "11--10", where "--" should be expressed
    # as "+"
    # The following maps those odd notations
    notation_map = { "+-": "-", "--": "+"}

    for o in allowed_operators:
      assert o in operations

    numbers = random.choices(range(min_value, max_value), k=dataset_size*2)

    sample = []
    for pair in zip(numbers[:dataset_size], numbers[dataset_size:]):
      operation_choice = random.choice(allowed_operators)
      result = operations[operation_choice](*pair)
      eq_literal = f'{pair[0]}{operation_choice}{pair[1]}'
      for notation in notation_map:
        if notation in eq_literal:
          eq_literal = eq_literal.replace(notation, notation_map[notation])
      
      sample.append((eq_literal, str(result)))
    return sample

To check the correctness of your implementation, use *test_generate_equations* function:

In [5]:
def test_generate_equations():
    allowed_operators = ['+', '-']
    dataset_size = 10
    for (input_, output_) in generate_equations(allowed_operators, dataset_size, 0, 100):
        if not (type(input_) is str and type(output_) is str):
            return "Both parts should be strings."
        if eval(input_) != int(output_):
            return "The (equation: {!r}, solution: {!r}) pair is incorrect.".format(input_, output_)
    return "Tests passed."

In [6]:
print(test_generate_equations())

Tests passed.


Finally, we are ready to generate the train and test data for the neural network:

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
allowed_operators = ['+', '-']
dataset_size = 100000
data = generate_equations(allowed_operators, dataset_size, min_value=0, max_value=9999)

train_set, test_set = train_test_split(data, test_size=0.2, random_state=42)

## Prepare data for the neural network

The next stage of data preparation is creating mappings of the characters to their indices in some vocabulary. Since in our task we already know which symbols will appear in the inputs and outputs, generating the vocabulary is a simple step.

#### How to create dictionaries for other task

First of all, you need to understand what is the basic unit of the sequence in your task. In our case, we operate on symbols and the basic unit is a symbol. The number of symbols is small, so we don't need to think about filtering/normalization steps. However, in other tasks, the basic unit is often a word, and in this case the mapping would be *word $\to$ integer*. The number of words might be huge, so it would be reasonable to filter them, for example, by frequency and leave only the frequent ones. Other strategies that your should consider are: data normalization (lowercasing, tokenization, how to consider punctuation marks), separate vocabulary for input and for output (e.g. for machine translation), some specifics of the task.

In [9]:
word2id = {symbol:i for i, symbol in enumerate('#^$+-1234567890')}
id2word = {i:symbol for symbol, i in word2id.items()}

#### Special symbols

In [10]:
start_symbol = '^'
end_symbol = '$'
padding_symbol = '#'

You could notice that we have added 3 special symbols: '^', '\$' and '#':
- '^' symbol will be passed to the network to indicate the beginning of the decoding procedure. We will discuss this one later in more details.
- '\$' symbol will be used to indicate the *end of a string*, both for input and output sequences. 
- '#' symbol will be used as a *padding* character to make lengths of all strings equal within one training batch.

People have a bit different habits when it comes to special symbols in encoder-decoder networks, so don't get too much confused if you come across other variants in tutorials you read. 

#### Padding

When vocabularies are ready, we need to be able to convert a sentence to a list of vocabulary word indices and back. At the same time, let's care about padding. We are going to preprocess each sequence from the input (and output ground truth) in such a way that:
- it has a predefined length *padded_len*
- it is probably cut off or padded with the *padding symbol* '#'
- it *always* ends with the *end symbol* '$'

We will treat the original characters of the sequence **and the end symbol** as the valid part of the input. We will store *the actual length* of the sequence, which includes the end symbol, but does not include the padding symbols. 

 Now you need to implement the function *sentence_to_ids* that does the described job. 

In [11]:
a = [1,2,3,4,5,6]

a[:3]

[1, 2, 3]

In [12]:
def sentence_to_ids(sentence, word2id, padded_len):
    """ Converts a sequence of symbols to a padded sequence of their ids.
    
      sentence: a string, input/output sequence of symbols.
      word2id: a dict, a mapping from original symbols to ids.
      padded_len: an integer, a desirable length of the sequence.

      result: a tuple of (a list of ids, an actual length of sentence).
    """
    # STUDENT CODE
    end_symbol = "$"
    pad_symbol = "#"
    sent_ids = [word2id[char] for char in sentence]
    # Trim sentence lenth (if need be) and add end symbol
    sent_ids = sent_ids[:(padded_len-1)] + [word2id[end_symbol]]
    sent_len = len(sent_ids)
    sent_ids = sent_ids + [word2id[pad_symbol] for pad in range(padded_len - sent_len)]
    
    
    return sent_ids, sent_len

Check that your implementation is correct:

In [13]:
def test_sentence_to_ids():
    sentences = [("123+123", 7), ("123+123", 8), ("123+123", 10)]
    expected_output = [([5, 6, 7, 3, 5, 6, 2], 7), 
                       ([5, 6, 7, 3, 5, 6, 7, 2], 8), 
                       ([5, 6, 7, 3, 5, 6, 7, 2, 0, 0], 8)] 
    for (sentence, padded_len), (sentence_ids, expected_length) in zip(sentences, expected_output):
        output, length = sentence_to_ids(sentence, word2id, padded_len)
        if output != sentence_ids:
            return("Convertion of '{}' for padded_len={} to {} is incorrect.".format(
                sentence, padded_len, output))
        if length != expected_length:
            return("Convertion of '{}' for padded_len={} has incorrect actual length {}.".format(
                sentence, padded_len, length))
    return("Tests passed.")

In [14]:
print(test_sentence_to_ids())

Tests passed.


We also need to be able to get back from indices to symbols:

In [15]:
def ids_to_sentence(ids, id2word):
    """ Converts a sequence of ids to a sequence of symbols.
    
          ids: a list, indices for the padded sequence.
          id2word:  a dict, a mapping from ids to original symbols.

          result: a list of symbols.
    """
 
    return [id2word[i] for i in ids] 

#### Generating batches

The final step of data preparation is a function that transforms a batch of sentences to a list of lists of indices. 

In [16]:
def batch_to_ids(sentences, word2id, max_len):
    """Prepares batches of indices. 
    
       Sequences are padded to match the longest sequence in the batch,
       if it's longer than max_len, then max_len is used instead.

        sentences: a list of strings, original sequences.
        word2id: a dict, a mapping from original symbols to ids.
        max_len: an integer, max len of sequences allowed.

        result: a list of lists of ids, a list of actual lengths.
    """
    
    max_len_in_batch = min(max(len(s) for s in sentences) + 1, max_len)
    batch_ids, batch_ids_len = [], []
    for sentence in sentences:
        ids, ids_len = sentence_to_ids(sentence, word2id, max_len_in_batch)
        batch_ids.append(ids)
        batch_ids_len.append(ids_len)
    return batch_ids, batch_ids_len

The function *generate_batches* will help to generate batches with defined size from given samples.

In [17]:
def generate_batches(samples, batch_size=64):
    X, Y = [], []
    for i, (x, y) in enumerate(samples, 1):
        X.append(x)
        Y.append(y)
        if i % batch_size == 0:
            yield X, Y
            X, Y = [], []
    if X and Y:
        yield X, Y

To illustrate the result of the implemented functions, run the following cell:

In [18]:
sentences = train_set[0]
ids, sent_lens = batch_to_ids(sentences, word2id, max_len=10)
print('Input:', sentences)
print('Ids: {}\nSentences lengths: {}'.format(ids, sent_lens))

Input: ('56+5235', '5291')
Ids: [[9, 10, 3, 9, 6, 7, 9, 2], [9, 6, 13, 5, 2, 0, 0, 0]]
Sentences lengths: [8, 5]


## Encoder-Decoder architecture

Encoder-Decoder is a successful architecture for Seq2Seq tasks with different lengths of input and output sequences. The main idea is to use two recurrent neural networks, where the first neural network *encodes* the input sequence into a real-valued vector and then the second neural network *decodes* this vector into the output sequence. While building the neural network, we will specify some particular characteristics of this architecture.

In [19]:
import tensorflow as tf

Let us use TensorFlow building blocks to specify the network architecture.

In [20]:
class Seq2SeqModel(object):
    pass

First, we need to create [placeholders](https://www.tensorflow.org/api_guides/python/io_ops#Placeholders) to specify what data we are going to feed into the network during the execution time. For this task we will need:
 - *input_batch* — sequences of sentences (the shape will equal to [batch_size, max_sequence_len_in_batch]);
 - *input_batch_lengths* — lengths of not padded sequences (the shape equals to [batch_size]);
 - *ground_truth* — sequences of groundtruth (the shape will equal to [batch_size, max_sequence_len_in_batch]);
 - *ground_truth_lengths* — lengths of not padded groundtruth sequences (the shape equals to [batch_size]);
 - *dropout_ph* — dropout keep probability; this placeholder has a predifined value 1;
 - *learning_rate_ph* — learning rate.

In [69]:
def declare_placeholders(self):
    """Specifies placeholders for the model."""
    # STUDENT CODE
    
    # Placeholders for input and its actual lengths.
    self.input_batch = tf.placeholder(shape=(None, None), dtype=tf.int32, name='input_batch')
    self.input_batch_lengths = tf.placeholder(shape=(None, ), dtype=tf.int32, name='input_batch_lengths')
    
    # Placeholders for groundtruth and its actual lengths.
    self.ground_truth = tf.placeholder(shape=(None, None), dtype=tf.int32, name='ground_truth')
    self.ground_truth_lengths = tf.placeholder(shape=(None, ), dtype=tf.int32, name='ground_truth_lengths')
        
    self.dropout_ph = tf.placeholder_with_default(tf.cast(1.0, tf.float32), shape=[])
    self.learning_rate_ph = tf.placeholder(shape=[], dtype=tf.float32, name="learning_rate_ph")

In [70]:
Seq2SeqModel.__declare_placeholders = classmethod(declare_placeholders)

Now, let us specify the layers of the neural network. First, we need to prepare an embedding matrix. Since we use the same vocabulary for input and output, we need only one such matrix. For tasks with different vocabularies there would be multiple embedding layers.
- Create embeddings matrix with [tf.Variable](https://www.tensorflow.org/api_docs/python/tf/Variable). Specify its name, type (tf.float32), and initialize with random values.
- Perform [embeddings lookup](https://www.tensorflow.org/api_docs/python/tf/nn/embedding_lookup) for a given input batch.

In [90]:
def create_embeddings(self, vocab_size, embeddings_size):
    """Specifies embeddings layer and embeds an input batch."""
    
    random_initializer = tf.random_uniform((vocab_size, embeddings_size), -1.0, 1.0)
    # STUDENT CODE
    self.embeddings = tf.Variable(dtype=tf.float32, 
                                  shape=(vocab_size, embeddings_size), 
                                  initial_value=random_initializer,
                                  name="embeddings")
    # STUDENT CODE
    # Perform embeddings lookup for self.input_batch. 
    self.input_batch_embedded = tf.nn.embedding_lookup(self.embeddings, self.input_batch)

In [91]:
Seq2SeqModel.__create_embeddings = classmethod(create_embeddings)

#### Encoder

The first RNN of the current architecture is called an *encoder* and serves for encoding an input sequence to a real-valued vector. Input of this RNN is an embedded input batch. Since sentences in the same batch could have different actual lengths, we also provide input lengths to avoid unnecessary computations. The final encoder state will be passed to the second RNN (decoder), which we will create soon. 

- TensorFlow provides a number of [RNN cells](https://www.tensorflow.org/api_guides/python/contrib.rnn#Core_RNN_Cells_for_use_with_TensorFlow_s_core_RNN_methods) ready for use. We suggest that you use [GRU cell](https://www.tensorflow.org/api_docs/python/tf/contrib/rnn/GRUCell), but you can also experiment with other types. 
- Wrap your cells with [DropoutWrapper](https://www.tensorflow.org/api_docs/python/tf/contrib/rnn/DropoutWrapper). Dropout is an important regularization technique for neural networks. Specify input keep probability using the dropout placeholder that we created before.
- Combine the defined encoder cells with [Dynamic RNN](https://www.tensorflow.org/api_docs/python/tf/nn/dynamic_rnn). Use the embedded input batches and their lengths here.
- Use *dtype=tf.float32* everywhere.

In [109]:
# STUDENT CODE
def build_encoder(self, hidden_size):
    """Specifies encoder architecture and computes its output."""
    
    # Create GRUCell with dropout.
    encoder_cell = tf.nn.rnn_cell.DropoutWrapper(
        tf.nn.rnn_cell.GRUCell(hidden_size, dtype=tf.float32),
        input_keep_prob = self.dropout_ph)    
    # Create RNN with the predefined cell.
    # See https://youtu.be/RIR_-Xlbp7s?t=1190
    _, self.final_encoder_state = tf.nn.dynamic_rnn(
        cell=encoder_cell, 
        inputs=self.input_batch_embedded,
        sequence_length = self.input_batch_lengths,
        dtype=tf.float32
    )

In [110]:
Seq2SeqModel.__build_encoder = classmethod(build_encoder)

#### Decoder

The second RNN is called a *decoder* and serves for generating the output sequence. In the simple seq2seq architecture, the input sequence is provided to the decoder only as the final state of the encoder. Obviously, it is a bottleneck and [Attention techniques](https://www.tensorflow.org/tutorials/seq2seq#background_on_the_attention_mechanism) can help to overcome it. So far, we do not need them to make our calculator work, but this would be a necessary ingredient for more advanced tasks. 

During training, decoder also uses information about the true output. It is feeded in as input symbol by symbol. However, during the prediction stage (which is called *inference* in this architecture), the decoder can only use its own generated output from the previous step to feed it in at the next step. Because of this difference (*training* vs *inference*), we will create two distinct instances, which will serve for the described scenarios.

The picture below illustrates the point. It also shows our work with the special characters, e.g. look how the start symbol `^` is used. The transparent parts are ignored. In decoder, it is masked out in the loss computation. In encoder, the green state is considered as final and passed to the decoder. 

<img src="https://github.com/gromag/natural-language-processing/blob/master/week4/encoder-decoder-pic.png?raw=1" style="width: 500px;">

Now, it's time to implement the decoder:
 - First, we should create two [helpers](https://www.tensorflow.org/api_guides/python/contrib.seq2seq#Dynamic_Decoding). These classes help to determine the behaviour of the decoder. During the training time, we will use [TrainingHelper](https://www.tensorflow.org/api_docs/python/tf/contrib/seq2seq/TrainingHelper). For the inference we recommend to use [GreedyEmbeddingHelper](https://www.tensorflow.org/api_docs/python/tf/contrib/seq2seq/GreedyEmbeddingHelper).
 - To share all parameters during training and inference, we use one scope and set the flag 'reuse' to True at inference time. You might be interested to know more about how [variable scopes](https://www.tensorflow.org/programmers_guide/variables) work in TF. 
 - To create the decoder itself, we will use [BasicDecoder](https://www.tensorflow.org/api_docs/python/tf/contrib/seq2seq/BasicDecoder) class. As previously, you should choose some RNN cell, e.g. GRU cell. To turn hidden states into logits, we will need a projection layer. One of the simple solutions is using [OutputProjectionWrapper](https://www.tensorflow.org/api_docs/python/tf/contrib/rnn/OutputProjectionWrapper).
 - For getting the predictions, it will be convinient to use [dynamic_decode](https://www.tensorflow.org/api_docs/python/tf/contrib/seq2seq/dynamic_decode). This function uses the provided decoder to perform decoding.

In [111]:
tf.expand_dims??
tf.concat??
# tf.fill??
tf.contrib.seq2seq.dynamic_decode??

import numpy as np

a = np.array([[[1, 1.2, 1.3], [2, 2.2, 2.3], [7, 7.2, 7.3]],
              [[3, 3.2, 3.3], [4, 4.2, 4.3], [8, 8.2, 8.3]],
              [[5, 5.2, 5.3], [6, 6.2, 6.3], [9, 9.2, 9.3]]]) 

with tf.Session() as sess:
  print(tf.strided_slice(a, [0, 0, 0], [3, 3, 3], [1, 1, 1]).eval())


[[[1.  1.2 1.3]
  [2.  2.2 2.3]
  [7.  7.2 7.3]]

 [[3.  3.2 3.3]
  [4.  4.2 4.3]
  [8.  8.2 8.3]]

 [[5.  5.2 5.3]
  [6.  6.2 6.3]
  [9.  9.2 9.3]]]


In [126]:
def build_decoder(self, hidden_size, vocab_size, max_iter, start_symbol_id, end_symbol_id):
    """Specifies decoder architecture and computes the output.
    
        Uses different helpers:
          - for train: feeding ground truth
          - for inference: feeding generated output

        As a result, self.train_outputs and self.infer_outputs are created. 
        Each of them contains two fields:
          rnn_output (predicted logits)
          sample_id (predictions).

    """
    
    # Use start symbols as the decoder inputs at the first time step.
    batch_size = tf.shape(self.input_batch)[0]
    start_tokens = tf.fill([batch_size], start_symbol_id)
    ground_truth_as_input = tf.concat([tf.expand_dims(start_tokens, 1), self.ground_truth], 1)
    
    # STUDENT CODE
    # TODO: revisit
    # Use the embedding layer defined before to lookup embeddings for ground_truth_as_input. 
    self.ground_truth_embedded = tf.nn.embedding_lookup(self.embeddings, ground_truth_as_input)
     
    # Create TrainingHelper for the train stage.
    train_helper = tf.contrib.seq2seq.TrainingHelper(self.ground_truth_embedded, 
                                                     self.ground_truth_lengths)
    # STUDENT CODE
    # TODO: revisit
    # Create GreedyEmbeddingHelper for the inference stage.
    # You should provide the embedding layer, start_tokens and index of the end symbol.
    infer_helper = tf.contrib.seq2seq.GreedyEmbeddingHelper(self.embeddings, start_tokens, end_symbol_id)
    
  
    def decode(helper, scope, reuse=None):
        """Creates decoder and return the results of the decoding with a given helper."""
        
        with tf.variable_scope(scope, reuse=reuse):
            # STUDENT CODE
            # Create GRUCell with dropout. Do not forget to set the reuse flag properly.
            decoder_cell = tf.nn.rnn_cell.DropoutWrapper(
              tf.nn.rnn_cell.GRUCell(hidden_size, dtype=tf.float32, reuse=reuse),
              input_keep_prob = self.dropout_ph) 
            
            # Create a projection wrapper.
            decoder_cell = tf.contrib.rnn.OutputProjectionWrapper(decoder_cell, vocab_size, reuse=reuse)
            
            # STUDENT CODE
            # Create BasicDecoder, pass the defined cell, a helper, and initial state.
            # The initial state should be equal to the final state of the encoder!
            decoder = tf.contrib.seq2seq.BasicDecoder(decoder_cell, helper, self.final_encoder_state)
            
            # The first returning argument of dynamic_decode contains two fields:
            #   rnn_output (predicted logits)
            #   sample_id (predictions)
            # see: https://youtu.be/RIR_-Xlbp7s?t=1844
            outputs, _, _ = tf.contrib.seq2seq.dynamic_decode(decoder=decoder, maximum_iterations=max_iter, 
                                                              output_time_major=False, impute_finished=True)

            return outputs
        
    self.train_outputs = decode(train_helper, 'decode')
    self.infer_outputs = decode(infer_helper, 'decode', reuse=True)

In [127]:
Seq2SeqModel.__build_decoder = classmethod(build_decoder)

In this task we will use [sequence_loss](https://www.tensorflow.org/api_docs/python/tf/contrib/seq2seq/sequence_loss), which is a weighted cross-entropy loss for a sequence of logits. Take a moment to understand, what is your train logits and targets. Also note, that we do not want to take into account loss terms coming from padding symbols, so we will mask them out using weights.  

In [140]:
tf.contrib.seq2seq.sequence_loss??
# tf.sequence_mask??
# # tf.cast??
# m = tf.cast(tf.sequence_mask([1,2,3,4]), dtype=tf.float32)
# with tf.Session() as sess:
#   print(m.eval())
tf.identity??

In [163]:
def compute_loss(self):
    """Computes sequence loss (masked cross-entopy loss with logits)."""
    
    weights = tf.cast(tf.sequence_mask(self.ground_truth_lengths), dtype=tf.float32)
    # STUDENT CODE
    # TODO: revisit
    self.loss = tf.contrib.seq2seq.sequence_loss(self.train_outputs.rnn_output, self.ground_truth, weights)

In [164]:
Seq2SeqModel.__compute_loss = classmethod(compute_loss)

The last thing to specify is the optimization of the defined loss. 
We suggest that you use [optimize_loss](https://www.tensorflow.org/api_docs/python/tf/contrib/layers/optimize_loss) with Adam optimizer and a learning rate from the corresponding placeholder. You might also need to pass global step (e.g. as tf.train.get_global_step()) and clip gradients by 1.0.

In [165]:
def perform_optimization(self):
    """Specifies train_op that optimizes self.loss."""

    # STUDENT CODE
    # see week2 assignment
    self.optimizer =  tf.train.AdamOptimizer(learning_rate=self.learning_rate_ph)
    self.grads_and_vars = self.optimizer.compute_gradients(self.loss)
    clip_norm = tf.cast(1.0, tf.float32)
    self.grads_and_vars = [(tf.clip_by_norm(g, clip_norm=clip_norm), v) for g, v in self.grads_and_vars]    
    self.train_op = self.optimizer.apply_gradients(self.grads_and_vars)

In [166]:
Seq2SeqModel.__perform_optimization = classmethod(perform_optimization)

Congratulations! You have specified all the parts of your network. You may have noticed, that we didn't deal with any real data yet, so what you have written is just recipies on how the network should function.
Now we will put them to the constructor of our Seq2SeqModel class to use it in the next section. 

In [167]:
def init_model(self, vocab_size, embeddings_size, hidden_size, 
               max_iter, start_symbol_id, end_symbol_id, padding_symbol_id):
    
    self.__declare_placeholders()
    self.__create_embeddings(vocab_size, embeddings_size)
    self.__build_encoder(hidden_size)
    self.__build_decoder(hidden_size, vocab_size, max_iter, start_symbol_id, end_symbol_id)
    
    # Compute loss and back-propagate.
    self.__compute_loss()
    self.__perform_optimization()
    
    # Get predictions for evaluation.
    self.train_predictions = self.train_outputs.sample_id
    self.infer_predictions = self.infer_outputs.sample_id

In [168]:
Seq2SeqModel.__init__ = classmethod(init_model)

## Train the network and predict output

[Session.run](https://www.tensorflow.org/api_docs/python/tf/Session#run) is a point which initiates computations in the graph that we have defined. To train the network, we need to compute *self.train_op*. To predict output, we just need to compute *self.infer_predictions*. In any case, we need to feed actual data through the placeholders that we defined above. 

In [169]:
def train_on_batch(self, session, X, X_seq_len, Y, Y_seq_len, learning_rate, dropout_keep_probability):
    # STUDENT CODE
    feed_dict = {
            self.input_batch: X,
            self.input_batch_lengths: X_seq_len,
            self.ground_truth: Y,
            self.ground_truth_lengths: Y_seq_len,
            self.learning_rate_ph: learning_rate,
            self.dropout_ph: dropout_keep_probability
        }
    pred, loss, _ = session.run([
            self.train_predictions,
            self.loss,
            self.train_op], feed_dict=feed_dict)
    return pred, loss

In [170]:
Seq2SeqModel.train_on_batch = classmethod(train_on_batch)

We implemented two prediction functions: *predict_for_batch* and *predict_for_batch_with_loss*. The first one allows only to predict output for some input sequence, while the second one could compute loss because we provide also ground truth values. Both these functions might be useful since the first one could be used for predicting only, and the second one is helpful for validating results on not-training data during the training.

In [171]:
def predict_for_batch(self, session, X, X_seq_len):
    # STUDENT CODE 
    feed_dict = {
            self.input_batch: X,
            self.input_batch_lengths: X_seq_len,
    }

    pred = session.run([
            self.infer_predictions
        ], feed_dict=feed_dict)[0]
    return pred

def predict_for_batch_with_loss(self, session, X, X_seq_len, Y, Y_seq_len):
    # STUDENT CODE
    feed_dict = {
            self.input_batch: X,
            self.input_batch_lengths: X_seq_len,
            self.ground_truth: Y,
            self.ground_truth_lengths: Y_seq_len,
    }    
    
    pred, loss = session.run([
            self.infer_predictions,
            self.loss,
        ], feed_dict=feed_dict)

    return pred, loss

In [172]:
Seq2SeqModel.predict_for_batch = classmethod(predict_for_batch)
Seq2SeqModel.predict_for_batch_with_loss = classmethod(predict_for_batch_with_loss)

## Run your experiment

Create *Seq2SeqModel* model with the following parameters:
 - *vocab_size* — number of tokens;
 - *embeddings_size* — dimension of embeddings, recommended value: 20;
 - *max_iter* — maximum number of steps in decoder, recommended value: 7;
 - *hidden_size* — size of hidden layers for RNN, recommended value: 512;
 - *start_symbol_id* — an index of the start token (`^`).
 - *end_symbol_id* — an index of the end token (`$`).
 - *padding_symbol_id* — an index of the padding token (`#`).

Set hyperparameters. You might want to start with the following values and see how it works:
- *batch_size*: 128;
- at least 10 epochs;
- value of *learning_rate*: 0.001
- *dropout_keep_probability* equals to 0.5 for training (typical values for dropout probability are ranging from 0.1 to 1.0); larger values correspond smaller number of dropout units;
- *max_len*: 20.

In [173]:
tf.reset_default_graph()

# STUDENT CODE
model = Seq2SeqModel(
            vocab_size = len(id2word), 
            embeddings_size = 20, 
            hidden_size = 512, 
            max_iter = 7, 
            start_symbol_id = word2id["^"], 
            end_symbol_id = word2id["$"], 
            padding_symbol_id = word2id["#"]
        )
# STUDENT CODE 
batch_size = 128
n_epochs = 10
learning_rate = 0.001
dropout_keep_probability = 0.5
max_len = 20

n_step = int(len(train_set) / batch_size)

Finally, we are ready to run the training! A good indicator that everything works fine is decreasing loss during the training. You should account on the loss value equal to approximately 2.7 at the beginning of the training and near 1 after the 10th epoch.

In [186]:
predictions = [[ 8,  6,  6, 14,  2,  0],
 [ 5, 10,  6,  6, 14,  2],
 [11, 14,  6,  5,  2,  0],
 [ 7, 13,  6,  9,  2,  0],
 [ 7, 13,  6,  9,  2,  0],
 [ 5, 12,  8,  2,  0,  0],
 [ 4, 12, 12,  8, 14,  2],
 [ 4,  5, 12,  8,  2,  0],
 [ 5,  6,  6,  6, 14,  2],
 [ 4,  5, 12, 12,  2,  0],
 [11, 13, 13,  5,  2,  0],
 [ 6, 13,  6,  5,  2,  0],
 [ 8,  6,  6,  7,  2,  0],
 [ 5,  6,  6,  6, 14,  2],
 [11, 14,  6, 14,  2,  0],
 [ 6, 13,  6,  2,  0,  0],
 [ 4,  5, 12,  6,  2,  0],
 [ 5,  6, 13,  6, 14,  2],
 [ 5, 10, 14,  6, 14,  2],
 [ 5,  6, 13,  6, 14,  2],
 [ 9, 13,  6, 14,  2,  0],
 [ 5,  8,  6,  6, 14,  2],
 [13, 13,  6, 14,  2,  0],
 [ 5,  8,  6,  6, 14,  2],
 [ 5, 12,  6,  2,  0,  0],
 [ 4, 11,  8,  8, 11,  2],
 [ 4,  5,  8,  6,  2,  0],
 [ 5, 12,  6,  2,  0,  0],
 [ 4,  6, 12,  8, 14,  2],
 [ 5,  6,  6,  6, 14,  2],
 [ 7,  6,  6,  7,  2,  0],
 [ 4,  5, 12,  8, 14,  2],
 [ 4,  8,  8,  8, 11,  2],
 [ 5, 14,  6,  5, 14,  2],
 [13, 13,  6, 14,  2,  0],
 [ 5, 14,  6,  6, 14,  2],
 [ 5,  8,  6,  6, 14,  2],
 [ 4,  8,  8,  8, 11,  2],
 [ 7, 13,  6,  9,  2,  0],
 [10, 14,  6, 14,  2,  0],
 [ 4,  8,  8,  8, 14,  2],
 [ 9, 13, 14, 14,  2,  0],
 [ 8,  6,  6,  5,  2,  0],
 [ 4,  8,  8,  6, 11,  2],
 [ 4,  5,  6, 12,  2,  0],
 [ 5, 12, 12,  2,  0,  0],
 [ 4,  5, 12, 12,  2,  0],
 [ 5, 14,  6,  6, 14,  2],
 [13, 13,  6, 14,  2,  0],
 [ 5,  6, 13,  6, 14,  2],
 [10, 13,  6,  5,  2,  0],
 [ 5, 12,  6,  2,  0,  0],
 [11, 14,  6, 14,  2,  0],
 [ 7, 12,  6,  7,  2,  0],
 [ 4, 11,  8,  8, 11,  2],
 [ 6, 12,  6,  2,  0,  0],
 [13, 13,  6, 14,  2,  0],
 [11, 14,  6,  6,  2,  0],
 [11, 13, 13,  5,  2,  0],
 [ 6, 12,  6,  2,  0,  0],
 [ 5, 12,  6,  2,  0,  0],
 [ 6,  6,  6,  7,  2,  0],
 [10, 13,  6, 14,  2,  0],
 [ 5, 10,  6,  6, 14,  2],
 [ 5,  6,  6,  6, 14,  2],
 [ 5,  6,  6,  6, 14,  2],
 [ 6, 12,  6,  2,  0,  0],
 [ 5, 14,  6,  6, 14,  2],
 [12, 13,  6, 14,  2,  0],
 [ 4,  5, 12, 12,  2,  0],
 [11, 14,  6, 14,  2,  0],
 [ 4,  6, 12,  8, 14,  2],
 [ 5,  6, 13,  6, 14,  2],
 [ 4,  5, 12, 12,  2,  0],
 [ 4, 11,  8,  8, 11,  2],
 [ 4, 12, 12,  8, 14,  2],
 [ 5,  6,  6,  6, 14,  2],
 [ 4,  8, 12,  8, 14,  2],
 [ 4,  8,  8,  8, 14,  2],
 [ 5, 11,  8,  6, 14,  2],
 [ 4,  5, 12,  8,  2,  0],
 [ 4,  8,  8,  8, 11,  2],
 [ 8, 13,  6, 14,  2,  0],
 [ 4,  5, 12,  8, 14,  2],
 [ 5, 12, 12,  2,  0,  0],
 [ 4,  8,  8,  8, 14,  2],
 [ 4, 11,  8,  8, 11,  2],
 [ 5, 11,  8,  6, 14,  2],
 [ 4,  5, 12,  8, 14,  2],
 [ 4,  5, 12,  8, 14,  2],
 [12, 13,  6, 14,  2,  0],
 [ 8, 13,  6,  5,  2,  0],
 [ 5,  8,  6,  6, 14,  2],
 [ 5,  8,  6,  6, 14,  2],
 [ 9,  7,  6,  7,  2,  0],
 [ 9, 13,  6, 14,  2,  0],
 [11, 14,  6, 14,  2,  0],
 [ 6, 12,  6,  2,  0,  0],
 [ 5, 14,  6,  6, 14,  2],
 [ 5, 11,  8,  6, 14,  2],
 [12, 13,  6, 14,  2,  0],
 [ 4,  5, 12,  8,  2,  0],
 [ 8,  6,  6, 14,  2,  0],
 [ 4, 11,  8,  8, 11,  2],
 [ 4,  6, 12,  8, 14,  2],
 [ 5, 12,  8,  2,  0,  0],
 [ 4,  8,  8,  6,  6,  2],
 [ 5,  6,  6,  6, 14,  2],
 [ 8,  6,  6,  7,  2,  0],
 [13, 13,  6, 14,  2,  0],
 [ 5,  6, 13,  6, 14,  2],
 [ 4, 11,  8, 11, 11,  2],
 [ 4,  8,  8,  8, 11,  2],
 [ 8,  6,  6,  5,  2,  0],
 [13, 13,  6, 14,  2,  0],
 [ 5,  6,  6,  6, 14,  2],
 [ 5, 14,  6,  5, 14,  2],
 [ 9, 13,  6,  5,  2,  0],
 [ 6, 13,  6,  5,  2,  0],
 [ 5, 12, 12,  2,  0,  0],
 [ 5, 14,  6,  5, 14,  2],
 [ 4,  5, 12,  8,  2,  0],
 [ 5,  6,  6,  6, 14,  2],
 [11, 14,  6,  6,  2,  0],
 [ 4,  5, 12, 12, 14,  2],
 [10, 14,  6, 14,  2,  0],
 [ 6, 12,  6,  2,  0,  0],
 [ 5,  6,  6,  6, 14,  2]]

In [188]:


  if(Y_batch_as_int[i]



In [ ]:
session = tf.Session()
session.run(tf.global_variables_initializer())
            
invalid_number_prediction_counts = []
all_model_predictions = []
all_ground_truth = []

print('Start training... \n')
for epoch in range(n_epochs):  
    random.shuffle(train_set)
    random.shuffle(test_set)
    
    print('Train: epoch', epoch + 1)
    for n_iter, (X_batch, Y_batch) in enumerate(generate_batches(train_set, batch_size=batch_size)):

        # STUDENT CODE
        # prepare the data (X_batch and Y_batch) for training
        # using function batch_to_ids
        X_batch_ids, X_seq_len = batch_to_ids(X_batch, word2id, max_len)
        Y_batch_ids, Y_seq_len = batch_to_ids(Y_batch, word2id, max_len)
        predictions, loss = model.train_on_batch(session, X_batch_ids, X_seq_len, Y_batch_ids, Y_seq_len, learning_rate, dropout_keep_probability)

        
        if n_iter % 200 == 0:
            print("Epoch: [%d/%d], step: [%d/%d], loss: %f" % (epoch + 1, n_epochs, n_iter + 1, n_step, loss))
                
    X_sent, Y_sent = next(generate_batches(test_set, batch_size=batch_size))
    # STUDENT CODE
    # prepare test data (X_sent and Y_sent) for predicting 
    # quality and computing value of the loss function
    # using function batch_to_ids
    X, X_seq_len = batch_to_ids(X_sent, word2id, max_len)
    Y, Y_seq_len = batch_to_ids(Y_sent, word2id, max_len)
    predictions, loss = model.predict_for_batch_with_loss(session, X, X_seq_len, Y, Y_seq_len)
    
    print('Test: epoch', epoch + 1, 'loss:', loss,)
    for x, y, p  in list(zip(X, Y, predictions))[:3]:
        print('X:',''.join(ids_to_sentence(x, id2word)))
        print('Y:',''.join(ids_to_sentence(y, id2word)))
        print('O:',''.join(ids_to_sentence(p, id2word)))
        print('')

    model_predictions = []
    ground_truth = []
    invalid_number_prediction_count = 0
    # STUDENT CODE
    # For the whole test set calculate ground-truth values (as integer numbers)
    # and prediction values (also as integers) to calculate metrics.
    # If generated by model number is not correct (e.g. '1-1'), 
    # increase invalid_number_prediction_count and don't append this and corresponding
    # ground-truth value to the arrays.
    for X_batch, Y_batch in generate_batches(test_set, batch_size=batch_size):
        Y_batch_as_int = [int(y) for y in Y_batch]
        ground_truth = ground_truth + [Y_batch_as_int]
        X_batch_ids, X_seq_len = batch_to_ids(X_batch, word2id, max_len)
        predictions = model.predict_for_batch(session, X_batch_ids, X_seq_len)
        for i, p in enumerate(predictions):
            output_padded = ids_to_sentence(p, id2word)
            output = output_padded[:output_padded.index('$')]
            output = ''.join(output)
            output_int = None
            try:
              output_int = int(output)
              if output_int != X_batch_as_int[i]:
                raise ValueError("Prediction did not match")
            except Exception as e:
              invalid_number_prediction_count +=1
              print(e)

            model_predictions = model_predictions + [output_int]              

    all_model_predictions.append(model_predictions)
    all_ground_truth.append(ground_truth)
    invalid_number_prediction_counts.append(invalid_number_prediction_count)
            
print('\n...training finished.')

Start training... 

Train: epoch 1
Epoch: [1/10], step: [1/625], loss: 2.716258


In [177]:
    for X_batch, Y_batch in generate_batches(test_set, batch_size=batch_size):
      Y_batch_as_int = [int(y) for y in Y_batch]
      print(Y_batch_as_int)

[10147, -3186, -4152, 4771, 18719, 1929, 13592, -5826, 11262, 5118, 7046, 18685, 6513, -4627, 12057, 4181, 18623, 5642, 357, 3099, 13845, 10823, -6311, -4000, -5971, 2049, 3364, -3630, 1795, 4445, 1658, -5578, 5702, 13012, 2467, 10271, 4396, 12467, 10689, 9410, 16345, 1144, 12940, 13224, 1891, 12281, -249, 8871, 9008, 7714, 10654, 7022, 10070, -6073, 5343, 17808, 18587, 6933, 95, 14533, 6869, -374, 12713, 4586, -3845, 869, 3132, 936, 191, 3403, -1345, 14731, 11626, 16109, -8539, 4832, 4601, 6714, 2286, -833, 5170, 18819, 10405, -1612, -220, 1923, 9110, 12101, 11810, 5452, 10242, 801, 6794, 4160, 2166, 9206, 14153, 14158, 18124, 7125, 554, 13929, 7919, 3311, 2358, 10919, 11465, 13716, 5290, 59, 10673, -1134, 685, -2936, 4559, 10965, 10525, 10496, 13221, 3277, 12359, 10090, -7864, 9945, 1549, 3502, -9154, 7337]
[9822, 10054, 6877, -5041, 12249, 7568, 2634, -7480, 13045, 8463, 4249, -1093, 6473, 8129, 7098, 2864, -1907, 14352, -1813, 16562, 748, -1014, 3953, 563, 6826, 7863, 4300, -5711, 

## Evaluate results

Because our task is simple and the output is straight-forward, we will use [MAE](https://en.wikipedia.org/wiki/Mean_absolute_error) metric to evaluate the trained model during the epochs. Compute the value of the metric for the output from each epoch.

In [ ]:
from sklearn.metrics import mean_absolute_error

In [ ]:
for i, (gts, predictions, invalid_number_prediction_count) in enumerate(zip(all_ground_truth,
                                                                            all_model_predictions,
                                                                            invalid_number_prediction_counts), 1):
    mae = ######### YOUR CODE HERE #############
    print("Epoch: %i, MAE: %f, Invalid numbers: %i" % (i, mae, invalid_number_prediction_count))